[workspace]
members = ["dist:."]

[package]
name = "spn"
version = "0.1.9"
repository = "https://github.com/tspader/spn"
binaries = ["spn"]
build-command = ["make", "dist"]

# Config for 'dist'
[dist]
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# Path that installers should place binaries in
install-path = "~/.local/bin"
# Whether to install an updater program
install-updater = false
# Which actions to run on pull requests
pr-run-mode = "upload"
