[package]
name = "gui"
version = "0.1.0"

[[bin]]
name = "main"
source = ["main.cpp"]
cxx = { standard = "c++17" }

[deps.package]
imgui = "1.92.8"
sdl3 = "3.4.15"

[config.imgui]
options = { sdl3 = true, sdlgpu3 = true }

[config.sdl3]
options = { x11 = true }

[profile.linux]
abi = "gnu"

[profile.macos]
toolchain = "clang"
