[package]
name = "spn_codegen"
repo = "tspader/sp"
version = "1.0.0"
commit = "fd9b5c03f181"
author = "tspader"
maintainer = "tspader"
description = "code generator"

[deps.package]
spn_schema = "1.0.0"

[[lib]]
name = "spn_codegen"
kinds = ["source"]
