#!/bin/sh
# Generated by spn install

export SPN_INCLUDES="-I/home/spader/.local/share/spn/cache/store/sdl3/2b03046c/include -I/home/spader/.local/share/spn/cache/store/sp/fee33525/include"
export SPN_LIB_INCLUDES="-L/home/spader/source/scratch/spn/examples/sdl/test_install/lib"
export SPN_LIBS="/home/spader/source/scratch/spn/examples/sdl/test_install/lib/libSDL3.so"
export SPN_FLAGS="$SPN_INCLUDES $SPN_LIB_INCLUDES $SPN_LIBS"
