[package]
name = "spn_alloc"
repo = "tspader/sp"
version = "1.0.0"
commit = "fd9b5c03f181"
author = "tspader"
maintainer = "tspader"
description = "memory allocator"

[deps.package]
spn_core = "1.0.0"

[lib]
kinds = ["source"]
