[package]
name = "spn_json"
repo = "tspader/sp"
version = "1.0.0"
commit = "fd9b5c03f181"
author = "tspader"
maintainer = "tspader"
description = "JSON parser"

[deps.package]
spn_simd = "1.0.0"

[lib]
kinds = ["source"]
