[package]
name = "sp"
url = "https://github.com/tspader/sp.git"
version = "1.6.6"
commit = "e15f48c662e0"
author = "tspader"
maintainer = "tspader"
system_deps = ["m"]

[[lib]]
name = "sp"
kinds = ["source"]

[options]
use_foo = false
