[package]
name = "spn_log"
repo = "tspader/sp"
version = "1.0.0"
commit = "fd9b5c03f181"
author = "tspader"
maintainer = "tspader"
description = "logging library"

[deps.package]
spn_alloc = "1.0.0"

[lib]
kinds = ["source"]
