include spn.mk

SPN_URL := foo
SPN_LIBS := clang

SPN_DIR_PROJECT := /home/spader/source/external/llvm-project
SPN_DIR_BUILD := /home/spader/source/scratch/sp-parse/build

spn-clone: $(SPN_DIR_PROJECT)

spn-build:
	mkdir -p $(SPN_DIR_BUILD)
	cd $(SPN_DIR_BUILD) && cmake -G Ninja $(SPN_DIR_PROJECT)/llvm \
		-DCMAKE_BUILD_TYPE=Release \
		-DLLVM_ENABLE_PROJECTS="clang" \
		-DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
		-DLLVM_BUILD_TOOLS=OFF \
		-DLLVM_BUILD_UTILS=OFF \
		-DLLVM_BUILD_EXAMPLES=OFF \
		-DLLVM_BUILD_TESTS=OFF \
		-DLLVM_BUILD_BENCHMARKS=OFF \
		-DLLVM_INCLUDE_TOOLS=ON \
		-DLLVM_INCLUDE_UTILS=OFF \
		-DLLVM_INCLUDE_EXAMPLES=OFF \
		-DLLVM_INCLUDE_TESTS=OFF \
		-DLLVM_INCLUDE_BENCHMARKS=OFF \
		-DLLVM_INCLUDE_DOCS=OFF \
		-DCLANG_BUILD_TOOLS=OFF \
		-DCLANG_TOOL_LIBCLANG_BUILD=ON \
		-DCLANG_INCLUDE_TESTS=OFF \
		-DCLANG_INCLUDE_DOCS=OFF \
		-DBUILD_SHARED_LIBS=OFF \
		-DLLVM_ENABLE_BINDINGS=OFF \
		-DLLVM_ENABLE_ASSERTIONS=OFF \
		-DLLVM_ENABLE_RTTI=ON
	cd $(SPN_DIR_BUILD) && ninja libclang
	mkdir -p $(SPN_DIR_STORE_BIN) $(SPN_DIR_STORE_INCLUDE)
	cp -r $(SPN_DIR_PROJECT)/clang/include/clang-c $(SPN_DIR_STORE_INCLUDE)/
	cp $(SPN_DIR_BUILD)/lib/libclang.so* $(SPN_DIR_STORE_BIN)/
