include spn.mk

SPN_URL := git@github.com:libsdl-org/SDL.git
SPN_LIBS := SDL3

HEADERS := $(SPN_DIR_STORE_INCLUDE)/SDL3
BINARY := $(SPN_DIR_STORE_BIN)/libSDL3.so

CMAKE_FLAG_DEFINES := -DCMAKE_BUILD_TYPE=Debug -DSDL_SHARED=ON -DSDL_STATIC=OFF -DSDL_TEST=OFF -DSDL_EXAMPLES=OFF
CMAKE_FLAGS := $(CMAKE_FLAG_DEFINES)

.PHONY: spn-clone spn-build

$(SPN_DIR_PROJECT):
	git clone $(SPN_URL) $(SPN_DIR_PROJECT)

$(BINARY):
	cmake -S$(SPN_DIR_PROJECT) -B$(SPN_DIR_BUILD) $(CMAKE_FLAGS)
	cmake --build $(SPN_DIR_BUILD) --parallel
	cp $(SPN_DIR_BUILD)/libSDL3.so $(SPN_DIR_STORE_BIN)

$(HEADERS):
	cp -r $(SPN_DIR_PROJECT)/include/SDL3 $(SPN_DIR_STORE_INCLUDE)

spn-clone: $(SPN_DIR_PROJECT)

spn-build: $(BINARY) $(HEADERS)
