SPN_URL := git@github.com:libsdl-org/SDL.git
SPN_LIBS := SDL3

include spn.mk

SDL3_H := $(SPN_DIR_STORE_INCLUDE)/SDL3
SDL3_SO := $(SPN_DIR_STORE_BIN)/libSDL3.so

CMAKE_FLAG_DEFINES := -DCMAKE_BUILD_TYPE=Debug -DSDL_SHARED=ON -DSDL_STATIC=OFF -DSDL_TEST=OFF -DSDL_EXAMPLES=OFF
CMAKE_FLAGS := $(CMAKE_FLAG_DEFINES)

.PHONY: spn-clone spn-build

$(SPN_DIR_PROJECT):
	git clone $(SPN_URL) $(SPN_DIR_PROJECT)

$(SDL3_SO):
	cmake -S$(SPN_DIR_PROJECT) -B$(SPN_DIR_BUILD) $(CMAKE_FLAGS)
	cmake --build $(SPN_DIR_BUILD) --parallel
	cp $(SPN_DIR_BUILD)/libSDL3.so $(SPN_DIR_STORE_BIN)

$(SDL3_H):
	cp -r $(SPN_DIR_PROJECT)/include/SDL3 $(SPN_DIR_STORE_INCLUDE)

spn-clone: $(SPN_DIR_PROJECT)

spn-build: $(SDL3_SO) $(SDL3_H)
