[package]
name = "spn_bar"
repo = "tspader/sp"
version = "1.0.0"
commit = "2365635171e7"
author = "tspader"
maintainer = "tspader"
description = "has a pkg dep"

[deps.package]
spn_baz = "1.0.0"

[lib]
kinds = ["source"]
