[package]
name = "toml"
url = "https://github.com/tspader/toml.git"
version = "1.2.1"
commit = "11a5889f1ff9"
author = "cktan"
maintainer = "tspader"
description = "A C99 and TOML 1.0.0 compliant TOML parser"

[lib]
kinds = ["source"]
