name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        if [ "$EUID" -ne 0 ]; then SUDO=sudo; fi
        ${SUDO:-} apt-get update
        ${SUDO:-} apt-get install -y build-essential cmake libelf-dev git libssl-dev libpsl-dev rsync

    - run: make bootstrap

    - run: make install

    - run: make ci

    - uses: actions/upload-artifact@v4
      if: ${{ !env.ACT }}
      with:
        name: build-artifacts
        path: build/
