name: smoke

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git libssl-dev libpsl-dev rsync

    - run: make smoke

    - uses: actions/upload-artifact@v4
      if: ${{ !env.ACT }}
      with:
        name: build-artifacts-${{ github.sha }}
        path: |
          build/bin/spn
          build/examples
